### ISSUE TITLE
"My name is …"

### ISSUE THREAD

**Issue by GPhMorin** [Algentem/Lernas#5]
- [x] La mayuskulo (M) ne esas aceptata;
- [x] Me kredas ke "Mea nomo esas …" esas anke korekta;
- [x] Forsan vera nomo (tala kam Luigi) esus plu interesanta kam tri punti.

**Comment by Algentem** [comment]
Me prizas la nomo Luigi!

**Comment by GPhMorin** [comment]
Me prizas Itala nomi, specale en Ido ;o)
